services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bands
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 200M